### ISSUE TITLE
Badge counts one less message, than there actually is

### ISSUE THREAD

**Issue by z0rc** [lpiepiora/docky-thunderbird#13]
Latest update fixed counter on KDE with Dock Manager, thanks! But the new problem appears. The badge always shows number by one less then the actual count of unread messages. E.g. `-1` with zero unread count, no badge with 1 unread, `1` with 2 unread and so on. If that helps, I'm using subfolders in inbox and "Count messages in subfolders" is checked.

**Comment by lpiepiora** [comment]
Thanks for your report. A new version 0.7.2 (currently in review), should fix this issue.
