### ISSUE TITLE
Incompatible with Thunderbird 6

### ISSUE THREAD

**Issue by fossfreedom** [lpiepiora/docky-thunderbird#9]
Guys,
  this question was recently asked on AskUbuntu - the originator said that this add-on was incompatible with Thunderbird 6 even if he overrode compatibility checks.

http://askubuntu.com/questions/57379/dockmanager-helper-for-thunderbird/58156#comment-66230

many thanks

fossfreedom

**Comment by lpiepiora** [comment]
I think this is very likely fixed in the latest version 0.7.1
